# Generated by Django 5.0.4 on 2026-03-24 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('region', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('jobs_scraped', models.IntegerField(default=0)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre du poste')),
                ('company', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_about', models.TextField(blank=True, verbose_name="À propos de l'entreprise")),
                ('location', models.CharField(max_length=200, verbose_name='Localisation')),
                ('country', models.CharField(choices=[('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('CM', 'Cameroun'), ('ML', 'Mali'), ('BF', 'Burkina Faso'), ('REMOTE', 'Remote / International'), ('AUTRE', 'Autre')], default='CI', max_length=10)),
                ('is_remote', models.BooleanField(default=False)),
                ('job_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('remote', 'Remote'), ('alternance', 'Alternance')], default='cdi', max_length=20)),
                ('domain', models.CharField(choices=[('it', 'Informatique & Tech'), ('data', 'Data & IA'), ('finance', 'Finance & Comptabilité'), ('marketing', 'Marketing & Com'), ('design', 'Design & Créatif'), ('rh', 'RH & Recrutement'), ('sante', 'Santé'), ('btp', 'BTP & Génie Civil'), ('commerce', 'Commerce & Ventes'), ('juridique', 'Juridique'), ('education', 'Éducation'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('missions', models.TextField(blank=True, verbose_name='Missions principales')),
                ('requirements', models.TextField(blank=True, verbose_name='Profil recherché')),
                ('required_skills', models.CharField(blank=True, max_length=1000)),
                ('nice_to_have', models.TextField(blank=True, verbose_name='Atouts supplémentaires')),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='FCFA', max_length=10)),
                ('salary_display_text', models.CharField(blank=True, max_length=200)),
                ('source_type', models.CharField(choices=[('scraping', 'Scraping automatique'), ('employer', 'Offre employeur'), ('manual', 'Saisie manuelle')], default='scraping', max_length=20)),
                ('external_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('view_count', models.IntegerField(default=0)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('scraping_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobsource')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['country', 'domain', 'is_active'], name='jobs_job_country_3d33c3_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active', 'posted_at'], name='jobs_job_is_acti_2e803c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('user', 'job')},
        ),
    ]
