# Generated by Django 3.2 on 2026-04-14 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name="Nom de l'alerte")),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='Mots-clés')),
                ('domain', models.CharField(blank=True, choices=[('it', 'Informatique & Tech'), ('data', 'Data & IA'), ('finance', 'Finance & Comptabilité'), ('marketing', 'Marketing & Com'), ('design', 'Design & Créatif'), ('rh', 'RH & Recrutement'), ('sante', 'Santé'), ('btp', 'BTP & Génie Civil'), ('commerce', 'Commerce & Ventes'), ('juridique', 'Juridique'), ('education', 'Éducation'), ('autre', 'Autre')], max_length=20)),
                ('job_type', models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('remote', 'Remote'), ('alternance', 'Alternance')], max_length=20)),
                ('country', models.CharField(blank=True, choices=[('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('NG', 'Nigeria'), ('GH', 'Ghana'), ('CM', 'Cameroun'), ('ML', 'Mali'), ('BF', 'Burkina Faso'), ('REMOTE', 'Remote / International'), ('AUTRE', 'Autre')], max_length=10)),
                ('min_score', models.IntegerField(default=60, verbose_name='Score minimum (%)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
