# Generated by Django 5.2.1 on 2026-04-15 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_add_job_interaction'),
        ('jobs', '0002_add_search_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobinteraction',
            name='unique_user_job_action',
        ),
        migrations.RemoveIndex(
            model_name='jobinteraction',
            name='jobinteract_user_action_idx',
        ),
        migrations.AddIndex(
            model_name='jobinteraction',
            index=models.Index(fields=['user', 'action', 'created_at'], name='application_user_id_39e091_idx'),
        ),
        migrations.AlterField(
            model_name='jobinteraction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='jobinteraction',
            unique_together={('user', 'job', 'action')},
        ),
    ]
