# Generated by Django 5.2.1 on 2026-04-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_jobinteraction_unique_user_job_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinteraction',
            name='action',
            field=models.CharField(choices=[('viewed', 'Vue'), ('saved', 'Sauvegardée'), ('applied', 'Candidature envoyée'), ('interested', "Ça m'intéresse"), ('dismissed', 'Pas intéressé')], max_length=20),
        ),
    ]
